#!/usr/bin/env python
# Newer, shinier mpdgrep using Python!
# Coded on the night of Sat, Oct 24, 2009 (7:15 PM to be exact!)
# JP St. Pierre <jstpierre@mecheye.net>

# Requires:
#   
#   mpd >= 0.16
#   
#   mpd-python (latest development build)
#     found at http://git.thejat.be/python-mpd.git/
#
#   lepl >= 3.3
#     run 'easy_install lepl' to get it

import sys
import os

from query import search, parse_bash_quotes, play, run

from twisted.internet import reactor

def main(client):
    terms = parse_bash_quotes(sys.argv[1:])

    # Check our results.
    if not terms:
        print "No query was entered."
        return
    
    results = search(terms, client)
    
    # If we have no results, exit.
    if not results:
        print "No results were found."
        return
    
    # Get the song ids and the current song id.
    currentfile = client.currentsong(blocking=True).get("file", None)
    
    # If the current song is in the
    # search results, go to the next
    # song. Make sure to mod len(songs).
    # Otherwise, start at the first song.
    index = 0
    for i, D in enumerate(results):
        if D['file'] == currentfile:
            index = (i+1)%len(results)
    
    # Print our results.
    for i, D in enumerate(results):
        print "%s%s - %s - %s" % (">" if i == index else " ", D.get('artist', ''), D.get('album', ''), D.get('title', ''))
    
    # Get the next song and play it.
    play(results[index]['file'], client)

    reactor.stop()

run(main)
