#!/bin/bash
. ~/.bashrc
echo "Removing playlist \"all\"."
(mpc rm all) > /dev/null
echo "Updating DB..."
(mpc update) > /dev/null
mpc idle database
echo "Adding new music..."
mpc clear
mpc add / > /dev/null
mpc save all
echo "Done..."